---
title: 'R Choropleth Demo: US Arrests for Murder by State'
author: "Brian High"
date: "Nov. 10th, 2015"
output:
  html_document:
    keep_md: yes
---

## Load Packages

```{r, choro0, echo=TRUE, eval=TRUE, message=FALSE, warning=TRUE}
# Install packages (if necessary)
for (pkg in c("ggmap", "dplyr")) {
    if (! suppressWarnings(require(pkg, character.only=TRUE)) ) {
        install.packages(pkg, repos="http://cran.fhcrc.org", dependencies=TRUE)
        if (! suppressWarnings(require(pkg, character.only=TRUE)) ) {
            stop(paste0(c("Can't load package: ", pkg, "!"), collapse = ""))
        }
    }
}
```

## Load Data

```{r, choro1, echo=TRUE, eval=TRUE}
# From: https://www3.amherst.edu/~nhorton/r2/examples/advanced.R
USArrests.st = mutate(USArrests, 
                      region=tolower(rownames(USArrests)),
                      murder = cut_number(Murder, 5))
us_state_map = map_data('state')
map_data = merge(USArrests.st, us_state_map, by="region")
map_data = arrange(map_data, order)
```

## Generate Choropleth Map

```{r, choro2, echo=TRUE, eval=TRUE, fig.height=4}
# From: https://www3.amherst.edu/~nhorton/r2/examples/advanced.R
p0 = ggplot(map_data, aes(x=long, y=lat, group=group)) +
    geom_polygon(aes(fill = murder)) +
    geom_path(colour='black') +
    theme(legend.position = "bottom", 
          panel.background=element_rect(fill="transparent",
                                        color=NA)) +
    scale_fill_grey(start=1, end =.1) + coord_map();
plot(p0)
```